#!/usr/bin/env python3

from sys import argv
from re import compile as regex, sub, MULTILINE, findall


USAGE = (
    'kvrprt source.kvr{lang}  # Creates: source.tal\n'
    'kvrprt source.tal  lang  # Creates: source.kvr{lang}'
)
LANGS = {
    'es': {
        'modes': ['2', 'c', 'r'],
        'opcodes': {
            'BRK': 'INT',
            'LIT': 'LIT',
            'INC': 'INC',
            'POP': 'RET',
            'NIP': 'COR',
            'SWP': 'CAM',
            'ROT': 'ROT',
            'DUP': 'DUP',
            'OVR': 'SOB',
            'EQU': 'IGU',
            'NEQ': 'NIG',
            'GTH': 'MAQ',
            'LTH': 'MEQ',
            'JMP': 'SAL',
            'JCN': 'SCN',
            'JSR': 'SRR',
            'STH': 'RES',
            'LDZ': 'CAC',
            'STZ': 'GUC',
            'LDR': 'CAR',
            'STR': 'GUR',
            'LDA': 'CAA',
            'STA': 'GUA',
            'DEI': 'DIE',
            'DEO': 'DIS',
            'ADD': 'SUM',
            'SUB': 'SUS',
            'MUL': 'MUL',
            'DIV': 'DIV',
            'AND': 'YNB',
            'ORA': 'ONB',
            'EOR': 'OEX',
            'SFT': 'DES'
        }
    },
    'eo': {
        'modes': ['2', 'k', 'r'],
        'opcodes': {
            'BRK': 'INT',
            'LIT': 'LIT',
            'INC': 'PGR',
            'POP': 'RET',
            'NIP': 'FOR',
            'SWP': 'ŜAĜ',
            'ROT': 'ROT',
            'DUP': 'DUP',
            'OVR': 'SUP',
            'EQU': 'EGA',
            'NEQ': 'NEG',
            'GTH': 'PGO',
            'LTH': 'MGO',
            'JMP': 'SAL',
            'JCN': 'SKN',
            'JSR': 'SRR',
            'STH': 'REZ',
            'LDZ': 'ŜAN',
            'STZ': 'KON',
            'LDR': 'ŜAR',
            'STR': 'KOR',
            'LDA': 'ŜAA',
            'STA': 'KOA',
            'DEI': 'END',
            'DEO': 'ELD',
            'ADD': 'ADI',
            'SUB': 'SUB',
            'MUL': 'MUL',
            'DIV': 'DIV',
            'AND': 'KBO',
            'ORA': 'ABO',
            'EOR': 'EKA',
            'SFT': 'ŜOV'
        }
    },
    'tok': {
        'modes': ['2', 'a', 'p'],
        'opcodes': {
            'BRK': 'PIN',
            'LIT': 'NAN',
            'INC': 'MUT',
            'POP': 'WEK',
            'NIP': 'WKP',
            'SWP': 'ANT',
            'ROT': 'SIK',
            'DUP': 'KIN',
            'OVR': 'KNP',
            'EQU': 'SAM',
            'NEQ': 'ALA',
            'GTH': 'SEW',
            'LTH': 'LIL',
            'JMP': 'TAW',
            'JCN': 'TWK',
            'JSR': 'TWP',
            'STH': 'POK',
            'LDZ': 'LKL',
            'STZ': 'STL',
            'LDR': 'LKP',
            'STR': 'STP',
            'LDA': 'LUK',
            'STA': 'SIT',
            'DEI': 'KUT',
            'DEO': 'TOK',
            'ADD': 'NSI',
            'SUB': 'NWE',
            'MUL': 'NKU',
            'DIV': 'NKI',
            'AND': 'LAL',
            'ORA': 'LAN',
            'EOR': 'LWA',
            'SFT': 'LTA'
        }
    }
}

def port_source(lang, source, target = 'en'):
    if lang == 'tal':
        opcodes = LANGS[target]['opcodes']
        modes = LANGS[target]['modes']
        _, k, r = modes
        for replacement, opcode in {v: k for k, v in opcodes.items()}.items():
            pattern = regex(rf'\b{opcode}(["2kr"]*)\b')
            source = pattern.sub(
                lambda match: replacement + ''.join([
                    k if mode == 'k' else 
                    r if mode == 'r' else 
                    mode for mode in match.group(1)]
                ), 
                source
            )
        return source

    kvr_comment = r'(\\ .*?)$'
    matches = findall(kvr_comment, source, flags=MULTILINE)
    for match in matches:
        subs = match.split('\\')[1].strip()
        source = source.replace(match, f"( {subs} )")
    if lang == 'en':
        return source
    opcodes = LANGS[lang]['opcodes']
    modes = LANGS[lang]['modes']
    _, k, r = modes
    for replacement, opcode in opcodes.items():
        pattern = regex(rf'\b{opcode}([{"".join(modes)}]*)\b')
        source = pattern.sub(
            lambda match: replacement + ''.join([
                'k' if mode == k else 
                'r' if mode == r else 
                mode for mode in match.group(1)]
            ), source
        )
    return source

def main():
    target = ''
    args_len = len(argv)
    if args_len < 2:
        print(USAGE)
    if args_len == 3:
        target = argv[2]
    file_name = argv[1]
    out_name = file_name.split('.')[0] + '.tal'
    with open(file_name, 'r') as file:
        source = file.read()

    if file_name.endswith('.kvr'):
        source = port_source('en', source)
    elif file_name.endswith('es'):
        source = port_source('es', source)
    elif file_name.endswith('eo'):
        source = port_source('eo', source)
    elif file_name.endswith('tok'):
        source = port_source('tok', source)
    elif file_name.endswith('.tal'):
        if target:
            source = port_source('tal', source, target)
            out_name = file_name.split('.')[0] + f'.kvr{target}'
        else:
            return
    else:
        print('file not recognized')

    with open(out_name, 'w') as file:
        file.write(source)


if __name__ == '__main__':
    main()